services:
  php:
    image: webdevops/php-apache-dev:8.1-alpine
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public/
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_MODE=off
    volumes:
      - .:/app
    ports:
      - 8000:80
    depends_on: [mariadb]

  mariadb:
    image: mariadb:10.4.22
    volumes:
      - database:/var/lib/mysql
      - .:/app
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dynamikdb
      MYSQL_USER: dynamik
      MYSQL_PASSWORD: dynamik

volumes:
  database: